
# base classifier thresholds
LOOP_TOLERANCE = .4
BASELINE_THRESHOLD = .5

# merge settings
HORIZONTAL_MERGE_THRESHOLD = 20
VERTICAL_MERGE_THRESHOLD = 20
WEAK_MERGE = True
HORIZONTAL_WEAK_MERGE_THRESHOLD = HORIZONTAL_MERGE_THRESHOLD
VERTICAL_WEAK_MERGE_THRESHOLD = VERTICAL_MERGE_THRESHOLD

# clustering settings
USE_LEV_DISTANCE = False
USE_GOWER_DISTANCE = not USE_LEV_DISTANCE
USE_TEXT = True
USE_FONT_DIST = True
USE_TOKENS = True
USE_LOOPS = True

# weigthing
TOKEN_WEIGHT = 1
LOOP_WEIGHT = 1
FONT_WEIGHT = 3
LEV_DIST_WEIGHT = 1
HORIZONTAL_SCALING = 0  # 0.001
DIAGONAL_SCALING = 0  # 0.001

# pre-classification
CLASSIFY_TEXT = True
CLASSIFY_LIST = True
CLASSIFY_PLOT = False
FLOAT_EPS = .001
